### ISSUE TITLE
CSS error in unpBootResources?

### ISSUE THREAD

**Issue by mickmoignardOAC** [whitemx/xcontrols-domino#299]
When using my Xcontrols app with a desktop browser, the app initialy opens with no styling and with errors are visible in the Chome dev console:
Failed to load resource: the server responded with a status of 404 (Not Found) https://mail.oacplc.net/Internal/Office/unp/unplugged-desktop.css 
Failed to load resource: the server responded with a status of 404 (Not Found)
https://mail.oacplc.net/Internal/Office/unp/css/bootcards-desktop.min.css 

which I think reflects these lines in the HTML:
`
<form id="view:_id1" method="post" action="/Internal/Office/OAC_CRM_Test_System.nsf/UnpMain.xsp" class="xspForm" enctype="multipart/form-data">
<link type="text/css" rel="stylesheet" href="unp/css/bootcards-desktop.min.css" unp-id="primarycss">
</link>
<link type="text/css" rel="stylesheet" href="unp/unplugged-desktop.css">
</link>
`
Note that the href for the two style sheets is missing the DBname.   Is that connected to lines 62 and 85 in UnpbootResources?

**Comment by mickmoignardOAC** [comment]
These are the missing lines from the HTML........
<form id="view:_id1" method="post" action="/Internal/Office/OAC_CRM_Test_System.nsf/UnpMain.xsp" class="xspForm" enctype="multipart/form-data">
<link type="text/css" rel="stylesheet" href="unp/css/bootcards-desktop.min.css" unp-id="primarycss">
</link>
<link type="text/css" rel="stylesheet" href="unp/unplugged-desktop.css">
</link>

**Comment by mickmoignardOAC** [comment]
One day I'll get past this markdown issue
    <form id="view:_id1" method="post" action="/Internal/Office/OAC_CRM_Test_System.nsf/UnpMain.xsp" class="xspForm" enctype="multipart/form-data">
<link type="text/css" rel="stylesheet" href="unp/css/bootcards-desktop.min.css" unp-id="primarycss">
</link>
<link type="text/css" rel="stylesheet" href="unp/unplugged-desktop.css">
</link>

**Comment by mickmoignardOAC** [comment]
'<form id="view:_id1" method="post" action="/Internal/Office/OAC_CRM_Test_System.nsf/UnpMain.xsp" class="xspForm" enctype="multipart/form-data">
<link type="text/css" rel="stylesheet" href="unp/css/bootcards-desktop.min.css" unp-id="primarycss">
</link>
<link type="text/css" rel="stylesheet" href="unp/unplugged-desktop.css">
</link>'

**Comment by mickmoignardOAC** [comment]
`<form id="view:_id1" method="post" action="/Internal/Office/OAC_CRM_Test_System.nsf/UnpMain.xsp" class="xspForm" enctype="multipart/form-data">
<link type="text/css" rel="stylesheet" href="unp/css/bootcards-desktop.min.css" unp-id="primarycss">
</link>
<link type="text/css" rel="stylesheet" href="unp/unplugged-desktop.css">
</link>`

**Comment by whitemx** [comment]
Those urls are relative so the files should load fine. Can you confirm that the file resources are available to anonymous users if the database has an all enabled.

**Comment by mickmoignardOAC** [comment]
Matt

It looked to me as tho the issue was that the URLs sent to the browser for those resources was malformed - missing the database name - and the server responded 404 and not 403.

Mick

________________________________
Mick Moignard
m: +44 7774 652504
Skype: mickmoignard

Sent from my iPad, so please excuse the typos.


> On 4 Feb 2015, at 19:46, Matt White <notifications@github.com> wrote:
> 
> Those urls are relative so the files should load fine. Can you confirm that the file resources are available to anonymous users if the database has an all enabled.
> 
> —
> Reply to this email directly or view it on GitHub.
> 




This email and any files transmitted with it are intended only for the person or entity to which it is addressed and may contain privileged or confidential information. If you're not the intended recipient, disclosing, copying, distributing or using this information is prohibited. If you've received this email in error, please contact the sender and delete all copies. This email may contain personal views which are not the views of OAC. We monitor our email system, and may record your emails.  OAC Actuaries and Consultants is a trading name of OAC plc. Registered office: 141-142 Fenchurch Street, London, EC3M 6BL, United Kingdom. Registered in England no. 4663795.

**Comment by mickmoignardOAC** [comment]
So what's happening over this issue? The resources are available; or at least, I think they are.  The chrome errors lead me to suspect that the URL being sent is missing the database name part, after Internal/Office and before.the CSS file name, so the server 404s the request.  I can see that happening in the Domlog.nsf.   It also now happens with Safari on iPhones and iPads. It seems that the initual load of the resources fails, but they get loaded later anc the browser then caches them.

**Comment by mickmoignardOAC** [comment]
???????????????????????????????????

**Comment by whitemx** [comment]
If you can send me the database design I can have a quick look, but from our side of things there is no issue. The URLs for the CSS files are relative so they don't need the database name. My guess is that the CSS is either not there, or is secured somehow.

**Comment by mickmoignardOAC** [comment]
Matt

Attached.  The issue is when unpMain is first opened...   Once you're past 
that, the issue sorts itself out. 

Mick


____________________________________________________

Mick Moignard
Software Developer
OAC Actuaries and Consultants

mick.moignard@oacplc.com  |  +44 (0)20 7278 9500  |  www.oacplc.com  |  
www.monetfinancialmodelling.com

Progress with Confidence

Follow us:  Twitter  |  LinkedIn

**Comment by whitemx** [comment]
I suspect the issue maybe that you're opening the URL http://myserver/Internal/Office/OAC_CRM_Test_System.nsf

What you actually need to open is http://myserver/Internal/Office/OAC_CRM_Test_System.nsf/UnpMain.xsp

**Comment by mickmoignardOAC** [comment]
I do open that, according to the database properties......

Mick

____________________________________________________

Mick Moignard
Software Developer
OAC Actuaries and Consultants

mick.moignard@oacplc.com  |  +44 (0)20 7278 9500  |  www.oacplc.com  |  
www.monetfinancialmodelling.com

Progress with Confidence

Follow us:  Twitter  |  LinkedIn

**Comment by whitemx** [comment]
The point is, simply setting the database properties is not sufficient, the URL you should open should include the UnpMain.xsp on the end.

**Comment by mickmoignardOAC** [comment]
Ah, OK. That's news to me that the database properties doesn't work 
correctly, then.

Mick

____________________________________________________

Mick Moignard
Software Developer
OAC Actuaries and Consultants

mick.moignard@oacplc.com  |  +44 (0)20 7278 9500  |  www.oacplc.com  |  
www.monetfinancialmodelling.com

Progress with Confidence

Follow us:  Twitter  |  LinkedIn

**Comment by mickmoignardOAC** [comment]
I'd also note that this CSS issue doesn't exist with apps created with the older Unplugged controls,   If I open the app there via the App Properties launch options, the CSS is all loaded as expected. I'd still say that this is a "feature" of XControls that could do with review.
