### ISSUE TITLE
Inline images in Notes document Rich Text shrunk to thumbnails in UnpBootFormViewer 

### ISSUE THREAD

**Issue by scottishdave** [whitemx/xcontrols-domino#317]
We have a Notes database with documents (created with the Notes client) such as the one attached with A5 sized inline images amongst text. When documents are displayed in a browser using UnpBootFormViewer rich text field renders inline images as thumbnails amongst the text (which remains as full size). Is there a way of keep the images in the same proportion as the text.
![thumbnailedimages](https://cloud.githubusercontent.com/assets/11050916/6792992/c7ee1172-d212-11e4-8e26-ad7542d0fa09.jpg)
![notesclientdocwithimage](https://cloud.githubusercontent.com/assets/11050916/6792995/cc4fd1f6-d212-11e4-83d8-9c1092afdbf7.jpg)

This is the rich field field setup

<div class="list-group-item">
	<xp:text id="clausetext" styleClass="richtextdisplay"
			value="#{docview.ClauseText}" escape="false">
	</xp:text>
</div>

**Comment by whitemx** [comment]
Added a new CSS Class: ".rtimage" which can be added to a rich text field. Any images in the rich text field will be scaled to their natural size or the maximum width of the card they are in, whichever is valid.
