### ISSUE TITLE
Font Awesome in iOS Blackberry Work Browser

### ISSUE THREAD

**Issue by ThorstenWGZ** [whitemx/xcontrols-domino#377]
Font Awesome Icons are not shown in Blackberry Work Browser for iOS on iPad.

**Comment by whitemx** [comment]
We've not done any testing on Blackberry I'm afraid. Which device are you using?

Are you able to see whether there are any errors in the Blackberry browser (sorry, never been a BB user so not sure if this is even possible).

**Comment by ThorstenWGZ** [comment]
Hi,

we are using the Blackberry App "Blackberry Work Browser" for iPad -> 
https://itunes.apple.com/de/app/work-browser-for-bes12/id645671461?mt=8
I could not find any error, even the domlog.nsf logs return codes 200/304 
for the font-awesome.css and other files.
I tested our own XControls-Application and your Sample Application, font 
awesome is not shown in both.

Maybe i should address this to Blackberry?

Mit freundlichen Grüßen/Best regards
Thorsten Meyer

WGZ BANK
Organisation und Betrieb
IT-Produktmanagement Business Intelligence und Kommunikation
Ludwig-Erhard-Allee 20
40227 Düsseldorf
____________________________________________________
Telefon:   +49 211 778 1686
Fax:          +49 211 778 4612



Von:    Matt White <notifications@github.com>
An:     whitemx/xcontrols-domino <xcontrols-domino@noreply.github.com>, 
Kopie:  ThorstenWGZ <thorsten.meyer@wgzbank.de>, Author 
<author@noreply.github.com>
Datum:  17.06.2016 14:07
Betreff:        Re: [whitemx/xcontrols-domino] Font Awesome in iOS 
Blackberry Work Browser (#377)



We've not done any testing on Blackberry I'm afraid. Which device are you 
using?
Are you able to see whether there are any errors in the Blackberry browser 
(sorry, never been a BB user so not sure if this is even possible).
?
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


__________

WGZ BANK AG Westdeutsche Genossenschafts-Zentralbank
Sitz: Düsseldorf, Registergericht: Amtsgericht Düsseldorf, HRB 52363

Vorstand: Hans-Bernd Wolberg (Vors.), Uwe Berghaus, 
Dr. Christian Brauckmann, Karl-Heinz Moll, Michael Speth
Vorsitzender des Aufsichtsrats: Werner Böhnke

Ueber das Internet versandte Nachrichten koennen unter fremdem Namen erstellt oder inhaltlich veraendert werden. Aus diesem Grund sind unsere als E-Mail verschickten Nachrichten grundsaetzlich keine rechtsverbindlichen Erklaerungen. Der Inhalt dieser E-Mail samt Anlagen ist vertraulich und u. U. rechtlich geschuetzt. Der Inhalt ist ausschließlich an einen bestimmten Empfaenger gerichtet. Eine Weitergabe, die Herstellung von Kopien oder der sonstige Gebrauch durch Nichtadressaten ist nicht erlaubt.
Messages sent via internet can be manipulated by third parties. For this reason our e-mail messages are generally not legally binding. This electronic message (including any attachments) contains confidential information and may be privileged or otherwise protected from disclosure. The information is intended to be for the use of the intended addressee only. Please be aware that any copy, distribution or use of the contents of this message by any other person than the intended addressee is prohibited.

**Comment by whitemx** [comment]
My guess would be that the embedded browser is not the most recent version of Safari. We only support the latest version of Safari in iOS9. If BB support come back with a fix, I can have a look at integrating it back into XControls.
