### ISSUE TITLE
Problem with custom buttons in UnpBootFormViewer

### ISSUE THREAD

**Issue by aka-lobo** [whitemx/xcontrols-domino#380]
Hi! 

I want to add a custom button to a Contact Details page from XControls Sampler. I put the button (with simple alert in it (events\onclick)) in component <xp:callback>, called _viewerbuttons._ on UnpBootFormViewer custom control.
![unpbootformviewer](https://cloud.githubusercontent.com/assets/20519984/17400436/aa46c4ee-5a69-11e6-8ae6-8c800065ce28.png)

When i open FlatView.xsp in a browser, with url http://hostname/sampler.nsf/FlatVies.xsp, this button is not working. 

![cistombuttonnotworking](https://cloud.githubusercontent.com/assets/20519984/17400786/bba43c38-5a6b-11e6-8c02-d83702bfc00e.png)

If i press 'reload page' in a browser, button starts to work, but if i click on another document in a list of contacts, button stops working again (until i reload browser page again).

![workafterreload](https://cloud.githubusercontent.com/assets/20519984/17400791/c07ac5a6-5a6b-11e6-85b8-e0a2936a69f5.png)

I guess I'm doing something wrong or is this a bug? How do I use custom buttons? 
ps. Thanks for your work!

**Comment by whitemx** [comment]
Hi there,

Generally you won't want to add buttons that XPages generates. When you load a document in XControls, it's loaded using Ajax, that means that any actions defined for the button will not be loaded. 

So you have two options: 

1: Define the button yourself using HTML and JavaScript
2: Change the UnpFlatList control which loads the document to stop using Ajax. Do this by setting the "ajaxload" custom property to "No"

Hope this helps.

Matt

**Comment by aka-lobo** [comment]
Matt, thanks for the help!  Your reply was very helpful.
